//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.venta_productos = new HashSet<venta_productos>();
        }
    
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string detalle_producto { get; set; }
        public decimal precio_actual { get; set; }
        public int unidades_disponibles { get; set; }
        public int id_categoria { get; set; }
        public int id_fabricante { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual fabricantes fabricantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta_productos> venta_productos { get; set; }
    }
}
